CREATE TABLE [dbo].[Table]
(
	[LAST NAME] NCHAR(10) NOT NULL , 
    [FIRST NAME] NCHAR(10) NOT NULL, 
    [EMPLOYEE ID] INT NOT NULL, 
    [PHOTO] IMAGE NOT NULL, 
    [DEPARTMENT] NCHAR(10) NOT NULL, 
    [DIVISION] NCHAR(10) NOT NULL, 
    PRIMARY KEY ([LAST NAME])
)
