#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HENRY")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAUTHOR(AUTHOR instance);
    partial void UpdateAUTHOR(AUTHOR instance);
    partial void DeleteAUTHOR(AUTHOR instance);
    partial void InsertBOOK(BOOK instance);
    partial void UpdateBOOK(BOOK instance);
    partial void DeleteBOOK(BOOK instance);
    partial void InsertBRANCH(BRANCH instance);
    partial void UpdateBRANCH(BRANCH instance);
    partial void DeleteBRANCH(BRANCH instance);
    partial void InsertINVENTORY(INVENTORY instance);
    partial void UpdateINVENTORY(INVENTORY instance);
    partial void DeleteINVENTORY(INVENTORY instance);
    partial void InsertPUBLISHER(PUBLISHER instance);
    partial void UpdatePUBLISHER(PUBLISHER instance);
    partial void DeletePUBLISHER(PUBLISHER instance);
    partial void InsertWROTE(WROTE instance);
    partial void UpdateWROTE(WROTE instance);
    partial void DeleteWROTE(WROTE instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ClassDemo.Properties.Settings.Default.HENRYConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AUTHOR> AUTHORs
		{
			get
			{
				return this.GetTable<AUTHOR>();
			}
		}
		
		public System.Data.Linq.Table<BOOK> BOOKs
		{
			get
			{
				return this.GetTable<BOOK>();
			}
		}
		
		public System.Data.Linq.Table<BRANCH> BRANCHes
		{
			get
			{
				return this.GetTable<BRANCH>();
			}
		}
		
		public System.Data.Linq.Table<INVENTORY> INVENTORies
		{
			get
			{
				return this.GetTable<INVENTORY>();
			}
		}
		
		public System.Data.Linq.Table<PUBLISHER> PUBLISHERs
		{
			get
			{
				return this.GetTable<PUBLISHER>();
			}
		}
		
		public System.Data.Linq.Table<WROTE> WROTEs
		{
			get
			{
				return this.GetTable<WROTE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AUTHOR")]
	public partial class AUTHOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _AUTHOR_NUM;
		
		private string _AUTHOR_LAST;
		
		private string _AUTHOR_FIRST;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAUTHOR_NUMChanging(decimal value);
    partial void OnAUTHOR_NUMChanged();
    partial void OnAUTHOR_LASTChanging(string value);
    partial void OnAUTHOR_LASTChanged();
    partial void OnAUTHOR_FIRSTChanging(string value);
    partial void OnAUTHOR_FIRSTChanged();
    #endregion
		
		public AUTHOR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHOR_NUM", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal AUTHOR_NUM
		{
			get
			{
				return this._AUTHOR_NUM;
			}
			set
			{
				if ((this._AUTHOR_NUM != value))
				{
					this.OnAUTHOR_NUMChanging(value);
					this.SendPropertyChanging();
					this._AUTHOR_NUM = value;
					this.SendPropertyChanged("AUTHOR_NUM");
					this.OnAUTHOR_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHOR_LAST", DbType="Char(12)")]
		public string AUTHOR_LAST
		{
			get
			{
				return this._AUTHOR_LAST;
			}
			set
			{
				if ((this._AUTHOR_LAST != value))
				{
					this.OnAUTHOR_LASTChanging(value);
					this.SendPropertyChanging();
					this._AUTHOR_LAST = value;
					this.SendPropertyChanged("AUTHOR_LAST");
					this.OnAUTHOR_LASTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHOR_FIRST", DbType="Char(10)")]
		public string AUTHOR_FIRST
		{
			get
			{
				return this._AUTHOR_FIRST;
			}
			set
			{
				if ((this._AUTHOR_FIRST != value))
				{
					this.OnAUTHOR_FIRSTChanging(value);
					this.SendPropertyChanging();
					this._AUTHOR_FIRST = value;
					this.SendPropertyChanged("AUTHOR_FIRST");
					this.OnAUTHOR_FIRSTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BOOK")]
	public partial class BOOK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BOOK_CODE;
		
		private string _TITLE;
		
		private string _PUBLISHER_CODE;
		
		private string _TYPE;
		
		private System.Nullable<decimal> _PRICE;
		
		private System.Nullable<char> _PAPERBACK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBOOK_CODEChanging(string value);
    partial void OnBOOK_CODEChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    partial void OnPUBLISHER_CODEChanging(string value);
    partial void OnPUBLISHER_CODEChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnPRICEChanging(System.Nullable<decimal> value);
    partial void OnPRICEChanged();
    partial void OnPAPERBACKChanging(System.Nullable<char> value);
    partial void OnPAPERBACKChanged();
    #endregion
		
		public BOOK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOK_CODE", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BOOK_CODE
		{
			get
			{
				return this._BOOK_CODE;
			}
			set
			{
				if ((this._BOOK_CODE != value))
				{
					this.OnBOOK_CODEChanging(value);
					this.SendPropertyChanging();
					this._BOOK_CODE = value;
					this.SendPropertyChanged("BOOK_CODE");
					this.OnBOOK_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="Char(40)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISHER_CODE", DbType="Char(3)")]
		public string PUBLISHER_CODE
		{
			get
			{
				return this._PUBLISHER_CODE;
			}
			set
			{
				if ((this._PUBLISHER_CODE != value))
				{
					this.OnPUBLISHER_CODEChanging(value);
					this.SendPropertyChanging();
					this._PUBLISHER_CODE = value;
					this.SendPropertyChanged("PUBLISHER_CODE");
					this.OnPUBLISHER_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Char(3)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAPERBACK", DbType="Char(1)")]
		public System.Nullable<char> PAPERBACK
		{
			get
			{
				return this._PAPERBACK;
			}
			set
			{
				if ((this._PAPERBACK != value))
				{
					this.OnPAPERBACKChanging(value);
					this.SendPropertyChanging();
					this._PAPERBACK = value;
					this.SendPropertyChanged("PAPERBACK");
					this.OnPAPERBACKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BRANCH")]
	public partial class BRANCH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _BRANCH_NUM;
		
		private string _BRANCH_NAME;
		
		private string _BRANCH_LOCATION;
		
		private System.Nullable<decimal> _NUM_EMPLOYEES;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBRANCH_NUMChanging(decimal value);
    partial void OnBRANCH_NUMChanged();
    partial void OnBRANCH_NAMEChanging(string value);
    partial void OnBRANCH_NAMEChanged();
    partial void OnBRANCH_LOCATIONChanging(string value);
    partial void OnBRANCH_LOCATIONChanged();
    partial void OnNUM_EMPLOYEESChanging(System.Nullable<decimal> value);
    partial void OnNUM_EMPLOYEESChanged();
    #endregion
		
		public BRANCH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_NUM", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal BRANCH_NUM
		{
			get
			{
				return this._BRANCH_NUM;
			}
			set
			{
				if ((this._BRANCH_NUM != value))
				{
					this.OnBRANCH_NUMChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_NUM = value;
					this.SendPropertyChanged("BRANCH_NUM");
					this.OnBRANCH_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_NAME", DbType="Char(50)")]
		public string BRANCH_NAME
		{
			get
			{
				return this._BRANCH_NAME;
			}
			set
			{
				if ((this._BRANCH_NAME != value))
				{
					this.OnBRANCH_NAMEChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_NAME = value;
					this.SendPropertyChanged("BRANCH_NAME");
					this.OnBRANCH_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_LOCATION", DbType="Char(50)")]
		public string BRANCH_LOCATION
		{
			get
			{
				return this._BRANCH_LOCATION;
			}
			set
			{
				if ((this._BRANCH_LOCATION != value))
				{
					this.OnBRANCH_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_LOCATION = value;
					this.SendPropertyChanged("BRANCH_LOCATION");
					this.OnBRANCH_LOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_EMPLOYEES", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> NUM_EMPLOYEES
		{
			get
			{
				return this._NUM_EMPLOYEES;
			}
			set
			{
				if ((this._NUM_EMPLOYEES != value))
				{
					this.OnNUM_EMPLOYEESChanging(value);
					this.SendPropertyChanging();
					this._NUM_EMPLOYEES = value;
					this.SendPropertyChanged("NUM_EMPLOYEES");
					this.OnNUM_EMPLOYEESChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INVENTORY")]
	public partial class INVENTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BOOK_CODE;
		
		private decimal _BRANCH_NUM;
		
		private System.Nullable<decimal> _ON_HAND;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBOOK_CODEChanging(string value);
    partial void OnBOOK_CODEChanged();
    partial void OnBRANCH_NUMChanging(decimal value);
    partial void OnBRANCH_NUMChanged();
    partial void OnON_HANDChanging(System.Nullable<decimal> value);
    partial void OnON_HANDChanged();
    #endregion
		
		public INVENTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOK_CODE", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BOOK_CODE
		{
			get
			{
				return this._BOOK_CODE;
			}
			set
			{
				if ((this._BOOK_CODE != value))
				{
					this.OnBOOK_CODEChanging(value);
					this.SendPropertyChanging();
					this._BOOK_CODE = value;
					this.SendPropertyChanged("BOOK_CODE");
					this.OnBOOK_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_NUM", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal BRANCH_NUM
		{
			get
			{
				return this._BRANCH_NUM;
			}
			set
			{
				if ((this._BRANCH_NUM != value))
				{
					this.OnBRANCH_NUMChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_NUM = value;
					this.SendPropertyChanged("BRANCH_NUM");
					this.OnBRANCH_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ON_HAND", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> ON_HAND
		{
			get
			{
				return this._ON_HAND;
			}
			set
			{
				if ((this._ON_HAND != value))
				{
					this.OnON_HANDChanging(value);
					this.SendPropertyChanging();
					this._ON_HAND = value;
					this.SendPropertyChanged("ON_HAND");
					this.OnON_HANDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PUBLISHER")]
	public partial class PUBLISHER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PUBLISHER_CODE;
		
		private string _PUBLISHER_NAME;
		
		private string _CITY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPUBLISHER_CODEChanging(string value);
    partial void OnPUBLISHER_CODEChanged();
    partial void OnPUBLISHER_NAMEChanging(string value);
    partial void OnPUBLISHER_NAMEChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    #endregion
		
		public PUBLISHER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISHER_CODE", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PUBLISHER_CODE
		{
			get
			{
				return this._PUBLISHER_CODE;
			}
			set
			{
				if ((this._PUBLISHER_CODE != value))
				{
					this.OnPUBLISHER_CODEChanging(value);
					this.SendPropertyChanging();
					this._PUBLISHER_CODE = value;
					this.SendPropertyChanged("PUBLISHER_CODE");
					this.OnPUBLISHER_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISHER_NAME", DbType="Char(25)")]
		public string PUBLISHER_NAME
		{
			get
			{
				return this._PUBLISHER_NAME;
			}
			set
			{
				if ((this._PUBLISHER_NAME != value))
				{
					this.OnPUBLISHER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PUBLISHER_NAME = value;
					this.SendPropertyChanged("PUBLISHER_NAME");
					this.OnPUBLISHER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="Char(20)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WROTE")]
	public partial class WROTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BOOK_CODE;
		
		private decimal _AUTHOR_NUM;
		
		private System.Nullable<decimal> _SEQUENCE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBOOK_CODEChanging(string value);
    partial void OnBOOK_CODEChanged();
    partial void OnAUTHOR_NUMChanging(decimal value);
    partial void OnAUTHOR_NUMChanged();
    partial void OnSEQUENCEChanging(System.Nullable<decimal> value);
    partial void OnSEQUENCEChanged();
    #endregion
		
		public WROTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOK_CODE", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BOOK_CODE
		{
			get
			{
				return this._BOOK_CODE;
			}
			set
			{
				if ((this._BOOK_CODE != value))
				{
					this.OnBOOK_CODEChanging(value);
					this.SendPropertyChanging();
					this._BOOK_CODE = value;
					this.SendPropertyChanged("BOOK_CODE");
					this.OnBOOK_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHOR_NUM", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal AUTHOR_NUM
		{
			get
			{
				return this._AUTHOR_NUM;
			}
			set
			{
				if ((this._AUTHOR_NUM != value))
				{
					this.OnAUTHOR_NUMChanging(value);
					this.SendPropertyChanging();
					this._AUTHOR_NUM = value;
					this.SendPropertyChanged("AUTHOR_NUM");
					this.OnAUTHOR_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQUENCE", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> SEQUENCE
		{
			get
			{
				return this._SEQUENCE;
			}
			set
			{
				if ((this._SEQUENCE != value))
				{
					this.OnSEQUENCEChanging(value);
					this.SendPropertyChanging();
					this._SEQUENCE = value;
					this.SendPropertyChanged("SEQUENCE");
					this.OnSEQUENCEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
